<a href="https://colab.research.google.com/github/annanya-mathur/Numpy-in-python/blob/main/Playing%20with%20arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
n1=np.array([10,20,30,40])          #creating numpy array
n1

array([10, 20, 30, 40])

In [4]:
n2=np.zeros((1,2))            #initializing numpy array with zeros
n2

array([[0., 0.]])

In [5]:
n3=np.arange(10,50,5)        #initializing numpy array with range(lowerlimit , upperlimit, intervals)
n3

array([10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
n4=np.random.randint(1,100,5)    #initializing numpy array with random numbers
n4

array([ 5, 42, 95, 95, 36])

In [29]:
#Joining numpy arrays
# vertically
n5=np.array([10,20,30])
n6=np.array([60,70,80])
n7=np.vstack((n5,n6))
n7

array([[10, 20, 30],
       [60, 70, 80]])

In [20]:
# By-column
np.column_stack((n5,n6))


array([[10, 60],
       [20, 70],
       [30, 80]])

In [19]:
#horizontally
np.hstack((n5,n6))

array([10, 20, 30, 60, 70, 80])

In [21]:
# Finding mean ,meadian ,standard deviation
# mean
np.mean(n1)

25.0

In [22]:
# meadian
np.median(n1)

25.0

In [23]:
# standard deviation
np.std(n1)

11.180339887498949

In [28]:
# Finding intersection and setdifference of two arrays
# intersection
np.intersect1d(n5,n1)

array([10, 20, 30])

In [27]:
# setdifference 
np.setdiff1d(n1,n5)

array([40])

In [32]:
# Finding shape/ dimensions of array
n7.shape

(2, 3)

In [37]:
# changing the shape / dimensions
n7.shape =(6,1)
n7

array([[10],
       [20],
       [30],
       [60],
       [70],
       [80]])